version: '3.9'

services:
  # Selenium Chrome service with VNC for visual debugging
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - VNC_NO_PASSWORD=1
      - START_XVFB=true
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 3s
      retries: 10
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount files to Chrome container where upload actually happens
      - "C:/Users/abhin/Downloads/surveysrs.pdf:/tmp/surveysrs.pdf:ro"
    networks:
      - attendance-management-shared-network

  # Test runner service
  selenium-tests:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: selenium-tests
    depends_on:
      chrome:
        condition: service_healthy

    environment:
      - PYTHONUNBUFFERED=1
      - TEST_LANGUAGE=Español
      - BASE_URL=${BASE_URL}
      - SELENIUM_HEADLESS=0
      - MOCK_MODE=0
      - SELENIUM_REMOTE_URL=http://chrome:4444/wd/hub
    volumes:
      - .:/app 
      # Also mount to test container for consistency
      - "C:/Users/abhin/Downloads/surveysrs.pdf:/tmp/surveysrs.pdf:ro"
    networks:
      - attendance-management-shared-network
    command: python -m pytest test_main_driver.py -v

networks:
  attendance-management-shared-network: